AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  DisplayCopNames: true
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'Gemfile*'
    - 'script/**/*'
    - 'test/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

### Style ###

Style/Documentation:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

### Layout ###

Layout/EndAlignment:
  Enabled: false

Layout/ElseAlignment:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

### Others ###

Lint/MissingSuper:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

