# frozen_string_literal: true

source 'https://rubygems.org'

ruby file: '../../.ruby-version'

gem 'rails', '~> 7.1.3.2'

gem 'lookbook', '~> 2.0'
gem 'puma', '~> 6.0'
gem 'sprockets-rails'
gem 'sqlite3'
gem 'stimulus-rails'
gem 'turbo-rails'

gem 'moonshot-rails', path: '../../'

group :development, :test do
  gem 'rspec-rails', '~> 6.1.0'
  gem 'webmock'
end
